eureka:
  instance:
    appname: eureka-client-two
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false
server:
  port: 8763
logging:
  file: "logs/eureka-client-two.log"
spring:
  application:
    name: eureka-client-two
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
